FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /src

RUN dotnet tool install --global dotnet-ef --version 9.0.19

ENV PATH="$PATH:/root/.dotnet/tools"

COPY . .

RUN dotnet restore "src/Services/Scoring/LoanPlatform.Scoring.Infrastructure/LoanPlatform.Scoring.Infrastructure.csproj"

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "src/Services/Scoring/LoanPlatform.Scoring.Infrastructure/LoanPlatform.Scoring.Infrastructure.csproj", "--startup-project", "src/Services/Scoring/LoanPlatform.Scoring.Api/LoanPlatform.Scoring.Api.csproj"]
