FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /src

RUN dotnet tool install --global dotnet-ef --version 9.0.19

ENV PATH="$PATH:/root/.dotnet/tools"

COPY . .

RUN dotnet restore "src/Services/LoanCore/LoanPlatform.LoanCore.Infrastructure/LoanPlatform.LoanCore.Infrastructure.csproj"

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "src/Services/LoanCore/LoanPlatform.LoanCore.Infrastructure/LoanPlatform.LoanCore.Infrastructure.csproj", "--startup-project", "src/Services/LoanCore/LoanPlatform.LoanCore.Api/LoanPlatform.LoanCore.Api.csproj"]
