FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore "src/ApiGateway/LoanPlatform.ApiGateway/LoanPlatform.ApiGateway.csproj"

RUN dotnet publish "src/ApiGateway/LoanPlatform.ApiGateway/LoanPlatform.ApiGateway.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "LoanPlatform.ApiGateway.dll"]
