<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>8ea4f325-5e5e-4122-b33f-c63b467e1827</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.19" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.19" />
        <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    </ItemGroup>

</Project>
